# Generated by Django 5.0.3 on 2024-11-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_employee_invoice_customuser_invoiceitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
